# Exclude a variety of commonly ignored directories.
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "notebooks/",
]

line-length = 120
indent-width = 4

# Assume Python 3.9
target-version = "py39"

[lint]
select = [
  "E",      # pycodestyle (style errors)
  "F",      # Pyflakes (logic issues like unused vars/imports)
  # "B",      # flake8-bugbear (common bugs)
  "I",      # isort (import sorting)
  "UP",     # pyupgrade (use modern Python features)
  # "C90",    # mccabe (cyclomatic complexity)
  "S",      # bandit (security issues)
  # "N",      # pep8-naming (PEP8 naming conventions)
]
ignore = ["E731", "S101"]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed.
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[format]
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

# Like Black, automatically detect the appropriate line ending.
line-ending = "auto"