_target_: src.model.BoltzmannGeneratorLitModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.0005
  betas:
    - 0.9
    - 0.999
  eps: 1e-8
  weight_decay: 0.01

# this does cosine annealing from max_lr to max_lr / div_factor / final_div_factor
# if pct_start != 0.0 you warmup from max_lr / div_factor to max_lr too
# normally you use this per-step but I've just got it per-epoch
scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  _partial_: true
  max_lr: ${model.optimizer.lr}
  total_steps: ${trainer.max_epochs}
  pct_start: 0.05
  anneal_strategy: cos
  cycle_momentum: false
  div_factor: 5e2
  final_div_factor: 1.0

jarzynski_sampler:
  _target_: src.models.components.jarzynski_sampler.JarzynskiSampler
  _partial_: true
  batch_size: ${data.batch_size}
  langevin_eps: 0.1
  num_timesteps: 10
  enabled: false
  ess_threshold: 0.0

sampling_config:
  num_proposal_samples: 10_000
  num_test_proposal_samples: 100_000
  num_jarzynski_samples: 100
  num_eval_samples: 5_000
  batch_size: 10_000
  energy_cutoff: null
  # Currently unused
  sampling_freq: 1
  jarzynski_freq: 1
  test_proposal_seed: 42
  save_samples_path: null

ema_decay: 0.999
eval_ema: true
eval_non_ema: false
# compile model for faster training with pytorch 2.0
compile: false
mean_free_prior: true
