defaults:
  - scheduler: cosine
  - optimizer: adam_w
_target_: src.model.BoltzmannGeneratorLitModule

# this does cosine annealing from max_lr to max_lr / div_factor / final_div_factor
# if pct_start != 0.0 you warmup from max_lr / div_factor to max_lr too
# normally you use this per-step but I've just got it per-epoch
smc_sampler:
  _target_: src.models.components.smc_sampler.SMCSampler
  _partial_: true
  batch_size: ${data.batch_size}
  langevin_eps: 0.1
  num_timesteps: 10
  enabled: false
  ess_threshold: 0.0
  input_energy_cutoff: null

sampling_config:
  num_proposal_samples: 10_000
  num_test_proposal_samples: 10_000
  num_smc_samples: 10_000
  num_eval_samples: 10_000
  batch_size: 10_000
  clip_reweighting_logits: 0.002

ema_decay: 0.999
eval_ema: true
eval_non_ema: false
# compile model for faster training with pytorch 2.0
compile: false
mean_free_prior: true
use_com_energy: false
