defaults:
  - default
  - net: egnn_dynamics_large

_target_: src.models.flow_matching_module.FlowMatchLitModule
mean_free_prior: True
atol: 1e-4
rtol: 1e-4
div_estimator: "exact"
logp_tol_scale: 1.0
n_eps: 1

optimizer:
  _partial_: true
  lr: 0.0005
  betas:
    - 0.9
    - 0.999
  eps: 1e-8
  weight_decay: 0.01

sampling_config:
  use_com_adjustment: False