defaults:
  - default

_target_: src.models.invertible_shortcut_module.InvertibleShortcutLitModule

net:
  _target_: src.models.components.tarflow.TarFlow
  img_size: 8
  in_channels: 1
  patch_size: 1
  channels: 64
  num_blocks: 3
  layers_per_block: 2

# base_flow:
#   _target_: src.models.shortcut_module.ShortcutLitModule
#   # it would be nice to read this stuff from elsewhere? idk
# 
#   net:
#     _target_: src.models.components.egnn_dynamics_consistency.EGNNDynamicsConsistency
#     n_particles: 4
#     n_dimension: 2
#   sampling_d_base: null
# 
# 
# 
d_base: 0
