defaults:
  - default

_target_: src.models.invertible_shortcut_module.InvertibleShortcutLitModule

net:
  _target_: src.models.components.tarflow.TarFlow
  img_size: 8
  in_channels: 1
  patch_size: 1
  channels: 64
  num_blocks: 3
  layers_per_block: 2

d_base: 0
base_flow_ckpt_path: null
