defaults:
  - default
  - net: tarflow
  - scheduler: cosine

_target_: src.models.normalizing_flow_module.NormalizingFlowLitModule
mean_free_prior: False

optimizer:
  lr: 1e-4
  betas:
    - 0.9
    - 0.95
  weight_decay: 4e-4
ema_decay: 0.999

sampling_config:
  use_com_adjustment: True