defaults:
  - default

_target_: src.models.shortcut_module.ShortcutLitModule

net:
  _target_: src.models.components.egnn_dynamics_consistency.EGNNDynamicsConsistency
  n_particles: 4
  n_dimension: 2

optimizer:
  lr: 0.001

sampling_d_base: null
