defaults:
  - model_checkpoint
  - model_checkpoint_cropped
  - early_stopping
  - model_summary
  - lr_monitor
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  monitor: "val/energy_w1"
  mode: "min"
  save_last: True
  save_top_k: 3
  auto_insert_metric_name: False

model_checkpoint_cropped:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}_cropped"
  monitor: "val/cropped_energy_w1"
  mode: "min"
  save_last: False
  save_top_k: 3
  auto_insert_metric_name: False

# early_stopping:
#   monitor: "val/acc"
#   patience: 100
#   mode: "max"

model_summary:
  max_depth: 2
