# @package _global_
#
defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    partition: long
    cpus_per_task: 4
    mem_gb: 48
    gres: gpu:1
    timeout_min: 2880
    array_parallelism: 100 # max num of tasks to run in parallel (via job array)
    setup:
      - "module purge"
      - "module load miniconda/3"
      - "module load cudatoolkit/12.4"
      - "micromamba activate tbg3"
    additional_parameters:
      nodelist: cn-a[001-011],cn-c[001-040],cn-l[001-087]
